# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd9d9720909e1ca70b36f903f7a7700f30dd7d32c4673f26a1276b3e2e72ba0b1db5ef3b8ea69b7b14009eb9d168d4d3020ef5b6b173bc943d1a9057765d781

test:
  secret_key_base: 36a029f5030ac970821963a885b2cde7de96db39c5328e6c2ba5cf057c8ee66bf8082fdbc48493cdc77aa571c35f9f0eb2cd7cbf4e50ff124091cf9d7b4ad254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
